# Generated by Django 5.1.4 on 2024-12-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ru',
        ),
    ]
