# Generated by Django 5.1.4 on 2024-12-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richman', '0002_remove_product_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='sold_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
